### ISSUE TITLE
Display fits image?

### ISSUE THREAD

**Issue by algady** [RononDex/FitsLibrary#3]
Can this be used to view (display) fits image? I mean to load and view the image itself!

**Comment by RononDex** [comment]
When it's a bit further along yes.

The library is still early work in progress. However, **next implementation step will be reading and accessing its data content**, once that's done you can use it to load the image data in fits files (which is what I want to use the library for myself)

**Comment by algady** [comment]
Great news, I'll be waiting for it, thanks

**Comment by RononDex** [comment]
Should not take too long hopefully, will keep you updated in this issue :)

**Comment by algady** [comment]
More good news, I'll consider help with donation, Keep up and thanks

**Comment by RononDex** [comment]
Just a small up date, have been working on the content parsing the past few days, should have it ready in 2-3 weeks I think

**Comment by RononDex** [comment]
A first nuget package is now released, with support for content parsing :)

Feel free to test it out and tell me how it works out for yout. It's just the first version though. I have several helper methods and stuff planned to make access a bit easier. However, it should be already quite self-explanatory on how to use it. See the ReadMe file for instructions
